# the name of the target operating system
SET(CMAKE_SYSTEM_NAME Windows)
SET(CMAKE_SYSTEM_PROCESSOR i686)

# which compilers to use for C and C++
SET(CMAKE_C_COMPILER i686-w64-mingw32-gcc)
SET(CMAKE_CXX_COMPILER i686-w64-mingw32-g++)
SET(CMAKE_RC_COMPILER i686-w64-mingw32-windres)


find_program(C_COMPILER_FULL_PATH i686-w64-mingw32-gcc)
get_filename_component(C_COMPILER_REALPATH ${C_COMPILER_FULL_PATH} REALPATH)
get_filename_component(C_COMPILER_PARENT_BIN ${C_COMPILER_REALPATH} REALPATH)
get_filename_component(C_COMPILER_PARENT_SYSROOT ${C_COMPILER_PARENT_BIN} REALPATH)

SET(CMAKE_FIND_ROOT_PATH ${C_COMPILER_PARENT_SYSROOT})

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

SET(PKG_CONFIG_EXECUTABLE "")
